
import React, { useState } from 'react';
import { ArrowLeft, Sparkles, Save, BookOpen, Layers, Type } from 'lucide-react';
import { askAiArchitect } from '../services/geminiService';
import { ContentPack, Chapter } from '../types';

interface ContentCreatorProps {
  onBack: () => void;
  onSavePack: (pack: ContentPack) => void;
}

const ContentCreator: React.FC<ContentCreatorProps> = ({ onBack, onSavePack }) => {
  const [topic, setTopic] = useState('');
  const [subject, setSubject] = useState('math');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<Partial<Chapter> | null>(null);

  const handleGenerate = async () => {
    if (!topic) return;
    setIsGenerating(true);

    // Prompt for Gemini to generate structured content
    const prompt = `Create a structured lesson plan for Indian rural students (Class 10) on the topic: "${topic}" in Subject: ${subject}. 
    Include:
    1. A simple summary in Hinglish (Hindi+English).
    2. Two multiple choice questions with explanations.
    Format the output as a clean text structure I can parse manually, or just provide the summary text for now.`;

    const response = await askAiArchitect(prompt, "Teacher Content Creator Tool");
    
    // Mock parsing or simple usage of response
    const mockChapter: Chapter = {
      id: `custom_${Date.now()}`,
      title: topic,
      summary: response.replace(/\n/g, '<br/>'), // Simple formatting
      isDownloaded: true,
      isCompleted: false,
      isLocked: false,
      quiz: [
        {
          id: 'q_gen_1',
          question: `Basic question about ${topic}?`,
          options: ["Option A", "Option B", "Option C", "Option D"],
          correctAnswer: 0,
          explanation: "Generated by AI based on context."
        }
      ]
    };

    setGeneratedContent(mockChapter);
    setIsGenerating(false);
  };

  const handleSave = () => {
    if (generatedContent) {
      const pack: ContentPack = {
        id: `pack_${Date.now()}`,
        title: generatedContent.title || 'Untitled Lesson',
        subjectId: subject,
        size: '1.2 MB',
        createdDate: new Date().toLocaleDateString(),
        version: 1,
        chapterData: generatedContent as Chapter
      };
      onSavePack(pack);
    }
  };

  return (
    <div className="h-full flex flex-col bg-slate-50 animate-slide-up">
      {/* Header */}
      <div className="h-16 border-b border-slate-200 flex items-center px-4 gap-3 bg-white sticky top-0 z-10">
        <button onClick={onBack} className="p-2 hover:bg-slate-100 rounded-full text-slate-600">
          <ArrowLeft />
        </button>
        <h2 className="font-bold text-slate-800 flex-1">Offline Content Studio</h2>
      </div>

      <div className="flex-1 overflow-y-auto p-4 md:p-8 max-w-3xl mx-auto w-full">
        {!generatedContent ? (
          <div className="space-y-6">
            <div className="bg-indigo-600 text-white p-6 rounded-2xl shadow-lg">
              <h3 className="text-xl font-bold mb-2 flex items-center gap-2">
                <Sparkles className="text-yellow-300" /> AI Lesson Generator
              </h3>
              <p className="text-indigo-200 opacity-90">
                Enter a topic, and our on-device AI model (simulated) will create a complete lesson pack with notes and quizzes for your students.
              </p>
            </div>

            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm space-y-4">
              <div>
                <label className="block text-sm font-bold text-slate-700 mb-1">Subject</label>
                <select 
                  value={subject} 
                  onChange={(e) => setSubject(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-indigo-500"
                >
                  <option value="math">Mathematics (Ganit)</option>
                  <option value="sci">Science (Vigyan)</option>
                  <option value="eng">English</option>
                  <option value="hist">History</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-bold text-slate-700 mb-1">Topic Name</label>
                <input 
                  type="text" 
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. Newton's Laws of Motion"
                  className="w-full bg-slate-50 border border-slate-200 rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>

              <button 
                onClick={handleGenerate}
                disabled={!topic || isGenerating}
                className="w-full bg-slate-900 text-white py-4 rounded-xl font-bold shadow-lg active:scale-95 transition-all flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                    Generating Lesson...
                  </>
                ) : (
                  <>
                    <Sparkles size={18} /> Generate Content
                  </>
                )}
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-6 animate-fade-in">
            <div className="flex items-center justify-between">
              <h3 className="text-2xl font-bold text-slate-800">Preview: {generatedContent.title}</h3>
              <button 
                onClick={() => setGeneratedContent(null)}
                className="text-slate-500 hover:text-red-500 text-sm font-bold"
              >
                Discard
              </button>
            </div>

            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h4 className="font-bold text-indigo-700 mb-4 flex items-center gap-2">
                <BookOpen size={18} /> Summary (Hinglish)
              </h4>
              <div 
                className="prose prose-sm prose-slate max-w-none bg-slate-50 p-4 rounded-lg border border-slate-100"
                dangerouslySetInnerHTML={{ __html: generatedContent.summary || '' }} 
              />
            </div>

            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
               <h4 className="font-bold text-orange-700 mb-4 flex items-center gap-2">
                <Layers size={18} /> Quiz Generated
              </h4>
              <div className="space-y-3">
                {generatedContent.quiz?.map((q, i) => (
                  <div key={i} className="bg-orange-50 p-3 rounded-lg border border-orange-100">
                    <p className="font-bold text-slate-800 text-sm">Q{i+1}: {q.question}</p>
                    <p className="text-xs text-slate-500 mt-1">Answer: {q.options[q.correctAnswer]}</p>
                  </div>
                ))}
              </div>
            </div>

            <button 
              onClick={handleSave}
              className="w-full bg-green-600 text-white py-4 rounded-xl font-bold shadow-lg hover:bg-green-700 active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              <Save size={20} /> Save & Create Content Pack
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default ContentCreator;
